version: '1.0'
services:
  mafia-server:
    build:
      context: .
    ports:
      - "65434:65434"
  redis:
    image: redis:7.0
    ports:
      - "6379:6379"
    command: redis-server --requirepass changeme