// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.22.3
// source: mafia.proto

package mafia

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Event:
	//
	//	*LoginResponse_PhaseChange_
	//	*LoginResponse_NewMessage_
	Event isLoginResponse_Event `protobuf_oneof:"event"`
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mafia_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mafia_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_mafia_proto_rawDescGZIP(), []int{0}
}

func (m *LoginResponse) GetEvent() isLoginResponse_Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (x *LoginResponse) GetPhaseChange() *LoginResponse_PhaseChange {
	if x, ok := x.GetEvent().(*LoginResponse_PhaseChange_); ok {
		return x.PhaseChange
	}
	return nil
}

func (x *LoginResponse) GetNewMessage() *LoginResponse_NewMessage {
	if x, ok := x.GetEvent().(*LoginResponse_NewMessage_); ok {
		return x.NewMessage
	}
	return nil
}

type isLoginResponse_Event interface {
	isLoginResponse_Event()
}

type LoginResponse_PhaseChange_ struct {
	PhaseChange *LoginResponse_PhaseChange `protobuf:"bytes,1,opt,name=phase_change,json=phaseChange,proto3,oneof"`
}

type LoginResponse_NewMessage_ struct {
	NewMessage *LoginResponse_NewMessage `protobuf:"bytes,2,opt,name=new_message,json=newMessage,proto3,oneof"`
}

func (*LoginResponse_PhaseChange_) isLoginResponse_Event() {}

func (*LoginResponse_NewMessage_) isLoginResponse_Event() {}

type LoginRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mafia_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mafia_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_mafia_proto_rawDescGZIP(), []int{1}
}

type EndTurnRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EndTurnRequest) Reset() {
	*x = EndTurnRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mafia_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EndTurnRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndTurnRequest) ProtoMessage() {}

func (x *EndTurnRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mafia_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndTurnRequest.ProtoReflect.Descriptor instead.
func (*EndTurnRequest) Descriptor() ([]byte, []int) {
	return file_mafia_proto_rawDescGZIP(), []int{2}
}

type EndTurnResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EndTurnResponse) Reset() {
	*x = EndTurnResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mafia_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EndTurnResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndTurnResponse) ProtoMessage() {}

func (x *EndTurnResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mafia_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndTurnResponse.ProtoReflect.Descriptor instead.
func (*EndTurnResponse) Descriptor() ([]byte, []int) {
	return file_mafia_proto_rawDescGZIP(), []int{3}
}

type VoteAgainstRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Target string `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
}

func (x *VoteAgainstRequest) Reset() {
	*x = VoteAgainstRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mafia_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VoteAgainstRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoteAgainstRequest) ProtoMessage() {}

func (x *VoteAgainstRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mafia_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoteAgainstRequest.ProtoReflect.Descriptor instead.
func (*VoteAgainstRequest) Descriptor() ([]byte, []int) {
	return file_mafia_proto_rawDescGZIP(), []int{4}
}

func (x *VoteAgainstRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

type VoteAgainstResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *VoteAgainstResponse) Reset() {
	*x = VoteAgainstResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mafia_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VoteAgainstResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoteAgainstResponse) ProtoMessage() {}

func (x *VoteAgainstResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mafia_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoteAgainstResponse.ProtoReflect.Descriptor instead.
func (*VoteAgainstResponse) Descriptor() ([]byte, []int) {
	return file_mafia_proto_rawDescGZIP(), []int{5}
}

type ShootRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Target string `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
}

func (x *ShootRequest) Reset() {
	*x = ShootRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mafia_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShootRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShootRequest) ProtoMessage() {}

func (x *ShootRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mafia_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShootRequest.ProtoReflect.Descriptor instead.
func (*ShootRequest) Descriptor() ([]byte, []int) {
	return file_mafia_proto_rawDescGZIP(), []int{6}
}

func (x *ShootRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

type ShootResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ShootResponse) Reset() {
	*x = ShootResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mafia_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShootResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShootResponse) ProtoMessage() {}

func (x *ShootResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mafia_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShootResponse.ProtoReflect.Descriptor instead.
func (*ShootResponse) Descriptor() ([]byte, []int) {
	return file_mafia_proto_rawDescGZIP(), []int{7}
}

type CheckRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Target string `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
}

func (x *CheckRequest) Reset() {
	*x = CheckRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mafia_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRequest) ProtoMessage() {}

func (x *CheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mafia_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRequest.ProtoReflect.Descriptor instead.
func (*CheckRequest) Descriptor() ([]byte, []int) {
	return file_mafia_proto_rawDescGZIP(), []int{8}
}

func (x *CheckRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

type CheckResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CheckResponse) Reset() {
	*x = CheckResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mafia_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckResponse) ProtoMessage() {}

func (x *CheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mafia_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckResponse.ProtoReflect.Descriptor instead.
func (*CheckResponse) Descriptor() ([]byte, []int) {
	return file_mafia_proto_rawDescGZIP(), []int{9}
}

type PublishCheckResultRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PublishCheckResultRequest) Reset() {
	*x = PublishCheckResultRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mafia_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PublishCheckResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishCheckResultRequest) ProtoMessage() {}

func (x *PublishCheckResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mafia_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishCheckResultRequest.ProtoReflect.Descriptor instead.
func (*PublishCheckResultRequest) Descriptor() ([]byte, []int) {
	return file_mafia_proto_rawDescGZIP(), []int{10}
}

type PublishCheckResultResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PublishCheckResultResponse) Reset() {
	*x = PublishCheckResultResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mafia_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PublishCheckResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishCheckResultResponse) ProtoMessage() {}

func (x *PublishCheckResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mafia_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishCheckResultResponse.ProtoReflect.Descriptor instead.
func (*PublishCheckResultResponse) Descriptor() ([]byte, []int) {
	return file_mafia_proto_rawDescGZIP(), []int{11}
}

type GetAlivePlayersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetAlivePlayersRequest) Reset() {
	*x = GetAlivePlayersRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mafia_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAlivePlayersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAlivePlayersRequest) ProtoMessage() {}

func (x *GetAlivePlayersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mafia_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAlivePlayersRequest.ProtoReflect.Descriptor instead.
func (*GetAlivePlayersRequest) Descriptor() ([]byte, []int) {
	return file_mafia_proto_rawDescGZIP(), []int{12}
}

type GetAlivePlayersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AlivePlayers []string `protobuf:"bytes,1,rep,name=alivePlayers,proto3" json:"alivePlayers,omitempty"`
}

func (x *GetAlivePlayersResponse) Reset() {
	*x = GetAlivePlayersResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mafia_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAlivePlayersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAlivePlayersResponse) ProtoMessage() {}

func (x *GetAlivePlayersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mafia_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAlivePlayersResponse.ProtoReflect.Descriptor instead.
func (*GetAlivePlayersResponse) Descriptor() ([]byte, []int) {
	return file_mafia_proto_rawDescGZIP(), []int{13}
}

func (x *GetAlivePlayersResponse) GetAlivePlayers() []string {
	if x != nil {
		return x.AlivePlayers
	}
	return nil
}

type LoginResponse_PhaseChange struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NewPhase string `protobuf:"bytes,1,opt,name=new_phase,json=newPhase,proto3" json:"new_phase,omitempty"`
}

func (x *LoginResponse_PhaseChange) Reset() {
	*x = LoginResponse_PhaseChange{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mafia_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginResponse_PhaseChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse_PhaseChange) ProtoMessage() {}

func (x *LoginResponse_PhaseChange) ProtoReflect() protoreflect.Message {
	mi := &file_mafia_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse_PhaseChange.ProtoReflect.Descriptor instead.
func (*LoginResponse_PhaseChange) Descriptor() ([]byte, []int) {
	return file_mafia_proto_rawDescGZIP(), []int{0, 0}
}

func (x *LoginResponse_PhaseChange) GetNewPhase() string {
	if x != nil {
		return x.NewPhase
	}
	return ""
}

type LoginResponse_NewMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *LoginResponse_NewMessage) Reset() {
	*x = LoginResponse_NewMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mafia_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginResponse_NewMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse_NewMessage) ProtoMessage() {}

func (x *LoginResponse_NewMessage) ProtoReflect() protoreflect.Message {
	mi := &file_mafia_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse_NewMessage.ProtoReflect.Descriptor instead.
func (*LoginResponse_NewMessage) Descriptor() ([]byte, []int) {
	return file_mafia_proto_rawDescGZIP(), []int{0, 1}
}

func (x *LoginResponse_NewMessage) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

var File_mafia_proto protoreflect.FileDescriptor

var file_mafia_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x6d, 0x61, 0x66, 0x69, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x6d,
	0x61, 0x66, 0x69, 0x61, 0x22, 0xf1, 0x01, 0x0a, 0x0d, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x45, 0x0a, 0x0c, 0x70, 0x68, 0x61, 0x73, 0x65, 0x5f,
	0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x6d,
	0x61, 0x66, 0x69, 0x61, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x2e, 0x50, 0x68, 0x61, 0x73, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x48, 0x00,
	0x52, 0x0b, 0x70, 0x68, 0x61, 0x73, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x42, 0x0a,
	0x0b, 0x6e, 0x65, 0x77, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x6d, 0x61, 0x66, 0x69, 0x61, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x4e, 0x65, 0x77, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x48, 0x00, 0x52, 0x0a, 0x6e, 0x65, 0x77, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x1a, 0x2a, 0x0a, 0x0b, 0x50, 0x68, 0x61, 0x73, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65,
	0x12, 0x1b, 0x0a, 0x09, 0x6e, 0x65, 0x77, 0x5f, 0x70, 0x68, 0x61, 0x73, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x65, 0x77, 0x50, 0x68, 0x61, 0x73, 0x65, 0x1a, 0x20, 0x0a,
	0x0a, 0x4e, 0x65, 0x77, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74,
	0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x42,
	0x07, 0x0a, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x22, 0x0e, 0x0a, 0x0c, 0x4c, 0x6f, 0x67, 0x69,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x10, 0x0a, 0x0e, 0x45, 0x6e, 0x64, 0x54,
	0x75, 0x72, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x11, 0x0a, 0x0f, 0x45, 0x6e,
	0x64, 0x54, 0x75, 0x72, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x2c, 0x0a,
	0x12, 0x56, 0x6f, 0x74, 0x65, 0x41, 0x67, 0x61, 0x69, 0x6e, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x22, 0x15, 0x0a, 0x13, 0x56,
	0x6f, 0x74, 0x65, 0x41, 0x67, 0x61, 0x69, 0x6e, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x26, 0x0a, 0x0c, 0x53, 0x68, 0x6f, 0x6f, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x22, 0x0f, 0x0a, 0x0d, 0x53, 0x68,
	0x6f, 0x6f, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x26, 0x0a, 0x0c, 0x43,
	0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x74,
	0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61, 0x72,
	0x67, 0x65, 0x74, 0x22, 0x0f, 0x0a, 0x0d, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1b, 0x0a, 0x19, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x43,
	0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x1c, 0x0a, 0x1a, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x43, 0x68, 0x65, 0x63,
	0x6b, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x18, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x69, 0x76, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x3d, 0x0a, 0x17, 0x47, 0x65, 0x74,
	0x41, 0x6c, 0x69, 0x76, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x61, 0x6c, 0x69, 0x76, 0x65, 0x50, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0c, 0x61, 0x6c, 0x69, 0x76,
	0x65, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x32, 0xd2, 0x03, 0x0a, 0x05, 0x4d, 0x61, 0x66,
	0x69, 0x61, 0x12, 0x34, 0x0a, 0x05, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x13, 0x2e, 0x6d, 0x61,
	0x66, 0x69, 0x61, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x14, 0x2e, 0x6d, 0x61, 0x66, 0x69, 0x61, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x30, 0x01, 0x12, 0x38, 0x0a, 0x07, 0x45, 0x6e, 0x64, 0x54,
	0x75, 0x72, 0x6e, 0x12, 0x15, 0x2e, 0x6d, 0x61, 0x66, 0x69, 0x61, 0x2e, 0x45, 0x6e, 0x64, 0x54,
	0x75, 0x72, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x6d, 0x61, 0x66,
	0x69, 0x61, 0x2e, 0x45, 0x6e, 0x64, 0x54, 0x75, 0x72, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x44, 0x0a, 0x0b, 0x56, 0x6f, 0x74, 0x65, 0x41, 0x67, 0x61, 0x69, 0x6e, 0x73,
	0x74, 0x12, 0x19, 0x2e, 0x6d, 0x61, 0x66, 0x69, 0x61, 0x2e, 0x56, 0x6f, 0x74, 0x65, 0x41, 0x67,
	0x61, 0x69, 0x6e, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x6d,
	0x61, 0x66, 0x69, 0x61, 0x2e, 0x56, 0x6f, 0x74, 0x65, 0x41, 0x67, 0x61, 0x69, 0x6e, 0x73, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x05, 0x53, 0x68, 0x6f, 0x6f,
	0x74, 0x12, 0x13, 0x2e, 0x6d, 0x61, 0x66, 0x69, 0x61, 0x2e, 0x53, 0x68, 0x6f, 0x6f, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x6d, 0x61, 0x66, 0x69, 0x61, 0x2e, 0x53,
	0x68, 0x6f, 0x6f, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x05,
	0x43, 0x68, 0x65, 0x63, 0x6b, 0x12, 0x13, 0x2e, 0x6d, 0x61, 0x66, 0x69, 0x61, 0x2e, 0x43, 0x68,
	0x65, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x6d, 0x61, 0x66,
	0x69, 0x61, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x59, 0x0a, 0x12, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x43, 0x68, 0x65, 0x63, 0x6b,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x20, 0x2e, 0x6d, 0x61, 0x66, 0x69, 0x61, 0x2e, 0x50,
	0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x6d, 0x61, 0x66, 0x69, 0x61,
	0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x50, 0x0a, 0x0f, 0x47,
	0x65, 0x74, 0x41, 0x6c, 0x69, 0x76, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x12, 0x1d,
	0x2e, 0x6d, 0x61, 0x66, 0x69, 0x61, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x69, 0x76, 0x65, 0x50,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e,
	0x6d, 0x61, 0x66, 0x69, 0x61, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x69, 0x76, 0x65, 0x50, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x2e, 0x5a,
	0x2c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x4d, 0x69, 0x6e, 0x6e,
	0x61, 0x6b, 0x68, 0x6d, 0x65, 0x74, 0x6f, 0x76, 0x2f, 0x73, 0x6f, 0x61, 0x2d, 0x70, 0x72, 0x61,
	0x63, 0x74, 0x69, 0x63, 0x65, 0x2d, 0x32, 0x2f, 0x6d, 0x61, 0x66, 0x69, 0x61, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_mafia_proto_rawDescOnce sync.Once
	file_mafia_proto_rawDescData = file_mafia_proto_rawDesc
)

func file_mafia_proto_rawDescGZIP() []byte {
	file_mafia_proto_rawDescOnce.Do(func() {
		file_mafia_proto_rawDescData = protoimpl.X.CompressGZIP(file_mafia_proto_rawDescData)
	})
	return file_mafia_proto_rawDescData
}

var file_mafia_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_mafia_proto_goTypes = []interface{}{
	(*LoginResponse)(nil),              // 0: mafia.LoginResponse
	(*LoginRequest)(nil),               // 1: mafia.LoginRequest
	(*EndTurnRequest)(nil),             // 2: mafia.EndTurnRequest
	(*EndTurnResponse)(nil),            // 3: mafia.EndTurnResponse
	(*VoteAgainstRequest)(nil),         // 4: mafia.VoteAgainstRequest
	(*VoteAgainstResponse)(nil),        // 5: mafia.VoteAgainstResponse
	(*ShootRequest)(nil),               // 6: mafia.ShootRequest
	(*ShootResponse)(nil),              // 7: mafia.ShootResponse
	(*CheckRequest)(nil),               // 8: mafia.CheckRequest
	(*CheckResponse)(nil),              // 9: mafia.CheckResponse
	(*PublishCheckResultRequest)(nil),  // 10: mafia.PublishCheckResultRequest
	(*PublishCheckResultResponse)(nil), // 11: mafia.PublishCheckResultResponse
	(*GetAlivePlayersRequest)(nil),     // 12: mafia.GetAlivePlayersRequest
	(*GetAlivePlayersResponse)(nil),    // 13: mafia.GetAlivePlayersResponse
	(*LoginResponse_PhaseChange)(nil),  // 14: mafia.LoginResponse.PhaseChange
	(*LoginResponse_NewMessage)(nil),   // 15: mafia.LoginResponse.NewMessage
}
var file_mafia_proto_depIdxs = []int32{
	14, // 0: mafia.LoginResponse.phase_change:type_name -> mafia.LoginResponse.PhaseChange
	15, // 1: mafia.LoginResponse.new_message:type_name -> mafia.LoginResponse.NewMessage
	1,  // 2: mafia.Mafia.Login:input_type -> mafia.LoginRequest
	2,  // 3: mafia.Mafia.EndTurn:input_type -> mafia.EndTurnRequest
	4,  // 4: mafia.Mafia.VoteAgainst:input_type -> mafia.VoteAgainstRequest
	6,  // 5: mafia.Mafia.Shoot:input_type -> mafia.ShootRequest
	8,  // 6: mafia.Mafia.Check:input_type -> mafia.CheckRequest
	10, // 7: mafia.Mafia.PublishCheckResult:input_type -> mafia.PublishCheckResultRequest
	12, // 8: mafia.Mafia.GetAlivePlayers:input_type -> mafia.GetAlivePlayersRequest
	0,  // 9: mafia.Mafia.Login:output_type -> mafia.LoginResponse
	3,  // 10: mafia.Mafia.EndTurn:output_type -> mafia.EndTurnResponse
	5,  // 11: mafia.Mafia.VoteAgainst:output_type -> mafia.VoteAgainstResponse
	7,  // 12: mafia.Mafia.Shoot:output_type -> mafia.ShootResponse
	9,  // 13: mafia.Mafia.Check:output_type -> mafia.CheckResponse
	11, // 14: mafia.Mafia.PublishCheckResult:output_type -> mafia.PublishCheckResultResponse
	13, // 15: mafia.Mafia.GetAlivePlayers:output_type -> mafia.GetAlivePlayersResponse
	9,  // [9:16] is the sub-list for method output_type
	2,  // [2:9] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_mafia_proto_init() }
func file_mafia_proto_init() {
	if File_mafia_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_mafia_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mafia_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mafia_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EndTurnRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mafia_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EndTurnResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mafia_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VoteAgainstRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mafia_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VoteAgainstResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mafia_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShootRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mafia_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShootResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mafia_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mafia_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mafia_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PublishCheckResultRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mafia_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PublishCheckResultResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mafia_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAlivePlayersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mafia_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAlivePlayersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mafia_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginResponse_PhaseChange); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mafia_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginResponse_NewMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_mafia_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*LoginResponse_PhaseChange_)(nil),
		(*LoginResponse_NewMessage_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mafia_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mafia_proto_goTypes,
		DependencyIndexes: file_mafia_proto_depIdxs,
		MessageInfos:      file_mafia_proto_msgTypes,
	}.Build()
	File_mafia_proto = out.File
	file_mafia_proto_rawDesc = nil
	file_mafia_proto_goTypes = nil
	file_mafia_proto_depIdxs = nil
}
